Matchat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('match.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

match/urls.py
from django.urls import path
from .views import index, user, reaction, chat
from .controller import reaction_controller, chat_controller

app_name = 'match'

urlpatterns = [
    path('', index.top, name='index'),
    path('login/', index.Login.as_view(), name='login'),
    path('logout/', index.Logout.as_view(), name='logout'),
    path('users/', user.gets, name='users'),
    path('users/regist/', user.regist, name='regist'),
    path('users/profile/<int:user_id>', user.profile),
    path('users/<int:user_id>/edit/', user.edit),
    path('reactions/', reaction_controller.create, name='reactions'),
    path('matching/', reaction.matching, name='matching'),  # 追加
    path('chat/create/<int:user_id>', chat.create, name='chat_create'),  # 追加
    path('chat/show/<int:room_id>', chat.show, name='chat_show'),  # 追加
    path('chat/show/<int:room_id>/messages/', chat.messages, name='chat_messages'),  # 追加
]

match/models/chatmessage.py
from django.db import models
from match.models.chatroom import ChatRoom
from match.models.userinfo import UserInfo


class ChatMessage(models.Model):
    chat_room = models.ForeignKey(ChatRoom, on_delete=False, related_name="message_roomid")
    user = models.ForeignKey(UserInfo, on_delete=False, related_name="message_userid")
    message = models.CharField(max_length=500)
    objects = models.Manager

match/models/chatroom.py
from django.db import models


class ChatRoom(models.Model):
    id = models.AutoField(primary_key=True)
    objects = models.Manager

match/models/chatroomuser.py
from django.db import models
from match.models.chatroom import ChatRoom
from match.models.userinfo import UserInfo


class ChatRoomUser(models.Model):
    chat_room = models.ForeignKey(ChatRoom, on_delete=False, related_name="roomuser_roomid")
    user = models.ForeignKey(UserInfo, on_delete=False, related_name="roomuser_userid")
    objects = models.Manager

match/models/image.py
from django.db import models
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill


class Image(models.Model):
   id = models.IntegerField(primary_key=True)
   objects = models.Manager
   origin = models.ImageField(upload_to="photos/%y/%m/%d/")

   # 画像をリサイズ
   big = ImageSpecField(source="origin",
                        processors=[ResizeToFill(1280, 1024)],
                        format='JPEG'
                        )

   thumbnail = ImageSpecField(source='origin',
                              processors=[ResizeToFill(250, 250)],
                              format="JPEG",
                              options={'quality': 60}
                              )

   middle = ImageSpecField(source='origin',
                           processors=[ResizeToFill(600, 400)],
                           format="JPEG",
                           options={'quality': 75}
                           )

   small = ImageSpecField(source='origin',
                          processors=[ResizeToFill(75, 75)],
                          format="JPEG",
                          options={'quality': 50}
                          )

match/models/reaction.py
from django.db import models
from match.models.userinfo import UserInfo

class Reaction(models.Model):
    id = models.IntegerField(primary_key=True)
    to_user = models.ForeignKey(UserInfo, on_delete=False, related_name="toid")
    from_user = models.ForeignKey(UserInfo, on_delete=False, related_name="fromid")
    status = models.IntegerField(primary_key=False)

match/models/userinfo.py
from django.db import models
from django.contrib.auth.models import User
from match.models.image import Image

# Create your models here.
class UserInfo(models.Model):
    image = models.OneToOneField(Image, on_delete=True)
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    self_introduction = models.CharField(max_length=500)
    sex = models.CharField(max_length=2)
    created_at = models.DateField(auto_now_add=True)
    objects = models.Manager

match/views/chat.py
from django.shortcuts import loader, redirect
from django.http import HttpResponse

from match.controller import chat_controller
from match.forms.chat import ChatForm
import json


def create(request, user_id):
    roomid = chat_controller.create(request.user.id, user_id)
    return redirect('/chat/show/' + str(roomid))


def show(request, room_id):
    form = ChatForm(request.GET)
    form.load(request.user.id, room_id)
    context = {
        'form': form
    }
    template = loader.get_template('chat.html')
    return HttpResponse(template.render(context, request))


def messages(request, room_id):
    context = chat_controller.messages(room_id)
    context_json = json.dumps(context)
    return HttpResponse(context_json)

match/views/index.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView

from match.forms.login import LoginForm

def top(request):
    return render(request, 'index.html')


class Login(LoginView):
    '''ログインページ'''
    form_class = LoginForm
    template_name = 'login.html'


class Logout(LogoutView, LoginRequiredMixin):
    '''ログアウトページ'''
    template_name = 'index.html'

match/views/reaction.py
from django.shortcuts import loader
from django.http import HttpResponse

from match.forms.reaction import ReactionForm

def matching(request):
    form = ReactionForm(request.GET)
    form.load(request.user.id)
    context = {
        'form': form
    }
    template = loader.get_template('matching.html')
    return HttpResponse(template.render(context, request))

match/views/user.py
from django.shortcuts import render, loader, redirect
from django.http import HttpResponse


from match.forms.user_regist import RegistForm
from match.forms.user_profile import ProfileForm
from match.forms.user_edit import EditForm
from match.forms.user_list import UserListForm

def regist(request):
    if request.method == 'GET':
        form = RegistForm()
    else:
        form = RegistForm(request.POST, request.FILES)
        if form.is_valid():
            print('user_regist is_valid')
            form.save(request.POST)
            return redirect('/login/')
        else:
            print('user_regist false is_valid')

    template = loader.get_template('regist.html')
    context = {
        'form': form,
    }
    return HttpResponse(template.render(context, request))


def gets(request):
    current_userid = request.user.id
    if request.method == 'GET':
        form = UserListForm(request.GET or None)
        form.load(current_userid)

    template = loader.get_template('users.html')
    context = {
        'form': form,
    }
    return HttpResponse(template.render(context, request))


def profile(request, user_id):
    if request.method == 'GET':
        form = ProfileForm(request.GET or None)
        form.load(user_id)  # 追加
        data = {
            'form': form,
            'iscurrent': request.user.id == user_id,
        }
        return render(request, 'profile.html', data)


def edit(request, user_id):
    if request.method == 'GET':
        form = EditForm(request.GET or None)
        form.load(user_id)
    else:
        form = EditForm(request.POST or None, request.FILES)
        if form.is_valid():
            print('user_edit is_valid')
            form.save(request.POST, user_id)
        else:
            print('user_edit false is_valid')
        if form.is_save:
            return redirect('/users/profile/' + str(id))

    template = loader.get_template('edit.html')
    context = {
        'form': form,
    }
    return HttpResponse(template.render(context, request))

templates/base.html
{% load static %}
{% load fontawesome %}
{% fontawesome_stylesheet %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

templates/chat.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/chat.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="{% static 'js/users.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <div class="chatPage">
        <header class="header">
            <a class="linkToMatching" href="/matching/"></a>
            <div class="chatPartner">
                <div class="chatPartner_img">
                    <img src="/media/{{ form.roomuser.user.image.origin }}">
                </div>
                <div class="chatPartner_name">{{ form.roomuser.user.name }}</div>
            </div>
        </header>
        <div class="container">
            <div class="messagesArea messages">
                {{ form.message }}
            </div>
        </div>
        <form class="messageInputForm">
            {% csrf_token %}
            <div class='container'>
                <input type="text" data-behavior="room_speaker" class="messageInputForm_input"
                       placeholder="メッセージを入力...">
            </div>
        </form>
    </div>
    <!-- ここから追加する -->
    <script>
        var username = '{{ form.current_user_name }}';
        var room_id = '{{ form.room_id }}';
        var user_id = '{{ form.roomuser.user.id }}';

        var chatSocket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/chat/' + room_id + '/');
        chatSocket.onmessage = function (e) {
            var data = JSON.parse(e.data);
            var username = data['username'];
            var message = data['message'];
            $('.messages').append(generateMessage(username, message));

        };
        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };
        $(document).on('keypress', '[data-behavior~=room_speaker]', function (event) {
            if (event.keyCode === 13) {
                chatSocket.send(JSON.stringify({
                    'message': event.target.value,
                    'username': username,
                    'room_id': room_id,
                    'user_id': user_id
                }));
                event.target.value = '';
                return event.preventDefault();
            }
        });
        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                }
            });
            $.ajax({
                type: "GET",
                url: "/chat/show/" + room_id + "/messages/",
                success: function (response) {
                    load_message_items = JSON.parse(response)
                    for (var index in load_message_items) {
                        var name = load_message_items[index].name
                        var message = load_message_items[index].message
                        $('.messages').append(generateMessage(name, message));
                    }
                }
            });
        });

        generateMessage = function (username, message) {
            return '<div class=\"message\">' +
                '<span>' + username + ':</span><div class="commonMessage"><div>' + message + '</div></div>' +
                '</div>';
        };
    </script>
    <!-- ここまで追加する -->
{% endblock %}

templates/edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/edit.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1">

<div class='userEditPage'>
    <div class='header'>アカウント編集</div>
    <div class='container'>
      <form class="edit_user" id="edit_user" enctype="multipart/form-data" action="/users/{{form.info.id}}/edit/" accept-charset="UTF-8" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {% for error_message in form.error_messages %}
            {{ error_message }}<br>
            {% endfor %}
            <label for="user_名前">名前</label>
            {{ form.username }}
          </div>
          <div class="form-group">
            <label for="user_自己紹介">自己紹介</label>
            {{ form.self_introduction }}
          </div>
          <div class="form-group">
            性別:
            {{ form.sex }}
          </div>
          <div class="form-group">
            画像:
            {{ form.image }}
          </div>
          <div class="form-group">
          <label for="user_更新するにはパスワードを入力してください">更新するにはパスワードを入力してください</label>
            {{form.password}}
          </div>
          <div class="text-center">
            {% buttons %}
            <input type="submit" class="btn submitBtn" value="更新" />
            {% endbuttons %}
          </div>
      </form>
    </div>
   </div>
   {% endblock %}

templates/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!--ここの行を追加する-->
<meta name="viewport" content="width=device-width, innitial-scale=1">

<div class="loginPage">
  <div class="container">
    <form method="POST" action="/login/">
        <div class="loginPage_contents">
            <h1 class="h3 loginPage_contents_title">新しいマッチを見つけよう</h1>
            {% csrf_token %}
            {% buttons %}
              <button type="submit" class="btn loginPage_contents_btn">
                  メールアドレスでログインする
              </button>
            {% endbuttons %}
          </div>
    </form>
  </div>
</div>

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="{% static 'js/users.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <div class='signinPage'>
        <div class='container'>
            <div class='userIcon'>
                <i class="fas fa-user fa-3x"></i>
            </div>
            <h2 class="title">ログイン</h2>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <div class="form-group text-center">
                    {% buttons %}
                        <button type="submit" class="loginBtn">
                            ログインする
                        </button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    {% endbuttons %}
                    <div class="linkToLogin"><a href="/users/regist/">アカウント作成はこちら</a></div>
                    {% csrf_token %}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/matching.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/matching.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="{% static 'js/users.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <div class="matchingPage">
        <header class="header">
            <i class="fas fa-comments fa-3x"></i>
            <div class="header_logo">
                <a href="/users">
                    <img src="{% static 'images/techpit-march-icon.png' %}" alt="Techpit march icon">
                </a>
            </div>
        </header>
        <div class="container">
            <div class="mt-5">
                <div class="matchingNum">
                    {{ form.count }}人とマッチングしています
                </div>
                <h2 class="pageTitle">マッチングした人一覧</h2>
                <div class="matchingList">
                    {% for matching in form.reaction_users %}
                        <div class="matchingPerson">
                            <div class="matchingPerson_img">
                                <img src="/media/{{ matching.to_user.image.origin }}">
                            </div>
                            <div class="matchingPerson_name">
                                {{ matching.to_user.name }}
                            </div>
                            <!-- ==========ここから追加する========== -->
                            <form action="/chat/create/{{ matching.to_user.id }}" accept-charset="UTF-8" method="post">
                                <input name="utf8" type="hidden" value="✓"><input type="hidden"
                                                                                  name="authenticity_token">
                                {% csrf_token %}
                                <input type="submit" name="commit" value="チャットを開く" class="chatForm_btn"
                                       data-disable-with="チャットを開く"/>
                            </form>
                            <!-- ==========ここまで追加する========== -->
                            </form>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<script src="{% static 'js/users.js' %}"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">

<div class='usershowPage'>
    <div class='container'>
        <header class="header">
        <p class='header_logo'>
            <a href="/users">
                <img src="{% static 'images/techpit-march-icon.png' %}" alt="Techpit march icon">
            </a>
        </p>
        </header>
        <div class='userInfo'>
            <div class='userInfo_img'>
                <img src="/media/{{ form.image.origin }}">
            </div>
            <div class='userInfo_name'>{{ form.info.name }}</div>
            <div class='userInfo_selfIntroduction'>
                {{ form.info.self_introduction }}
            </div>
        </div>
        {% if iscurrent %}
        <div class='userAction'>
            <div class="userAction_edit userAction_common">
            <a href="/users/{{ form.info.id }}/edit"><i class="fas fa-edit fa-2x"></i></a>
            <span>情報を編集</span>
            </div>
            <div class='userAction_logout userAction_common'>
            <a rel="nofollow" data-method="delete" href="/"><i class="fas fa-cog fa-2x"></i></a>
            <span>ログアウト</span>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/regist.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/regist.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="{% static 'js/users.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <div class="sinupPage">
        <header class="header">
            <div>アカウントを作成</div>
        </header>
        <div class='container'>
            <form class="mt-5" id="new_user" enctype="multipart/form-data" accept-charset="UTF-8" method="POST"
                  action="{% url 'match:regist' %}">
                {% csrf_token %}
                <input name="utf8" type="hidden" value="✓">
                <input type="hidden" name="authenticity_token"
                       value="s8O7UsW45y0Qa6t3y1hARPTt0Y2XupNHiCcK9e7PphbZBj5R9r8nPP9eLLEGvN4jLb8XMnedE8oH3hwIkbAKYw==">
                {% for error_message in form.error_messages %}
                    {{ error_message }}<br>
                {% endfor %}
                <label for="id_image" class="rounded-circle userProfileImg">
                    <div class="userProfileImg_description">画像をアップロード</div>
                    <i class="fas fa-camera fa-3x"></i>
                    {{ form.image }}
                </label>

                <div class="userImgPreview" id="userImgPreview">
                    <img id="thumbnail" class="userImgPreview_content" accept="image/*" src="">
                    <p class="userImgPreview_text">画像をアップロード済み</p>
                </div>
                <div class="form-group">
                    <label>名前</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label>Eメールアドレス</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label>パスワード</label>
                    <em>{{ form.password_error_message }}</em>
                    <br/>
                    {{ form.password1 }}
                </div>
                <div class="form-group">
                    <label>確認用パスワード</label>
                    {{ form.password2 }}
                </div>
                <div class="form-group">
                    <div><label for=''>性別</label></div>
                    {{ form.sex }}
                </div>
                <div class="form-group">
                    <label>自己紹介文</label>
                    {{ form.self_introduction }}
                </div>
                <div class="text-center">
                    {% buttons %}
                        <input type="submit" class="btn submitBtn" value="はじめる"/>
                    {% endbuttons %}
                    <div class="linkToLogin"><a href="/login/">ログインはこちら</a></div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/top.html
{% load static %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<meta name="viewport" content="width=device-width, initial-scale=1">

<div class="topPage">
</div>

templates/users.html
{% load static %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
      integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/jTinder.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/users.css' %}">

<script src="{% static 'js/jquery.jTinder.js' %}"></script>
<script src="{% static 'js/jquery.transform2d.js' %}"></script>
<div class="topPage">

    <nav class="nav">
        <ul>
            <li class="personIcon">
                <a href="/users/profile/{{ form.currentuser_id }}">
                    <i class="fas fa-2x fa-user"></i>
                </a>
            </li>
            <li class="appIcon">
                <a href="/users">
                    <img src="{% static 'images/techpit-march-icon.png' %}" alt="Techpit march icon">
                </a>
            </li>
            <li class="messageIcon">
                <a href="/matching">
                    <i class="fas fa-2x fa-comments"></i>
                </a>
            </li>
        </ul>
    </nav>
    <div id="tinderslide">
        <ul>

            {% for user in form.exclude_userlist %}
                <li data-user_id="{{ user.id }}">
                    <div class="userName">{{ user.name }}</div>
                    <img src="/media/{{ user.image.origin }}">
                    <div class="like"></div>
                    <div class="dislike"></div>
                </li>
            {% endfor %}
        </ul>
        <div class="noUser">近くにお相手がいません。</div>
    </div>
    <div class="actions" id="actionBtnArea">
        {% csrf_token %}
        <a href="#" class="dislike"><i class="fas fa-times fa-2x"></i></a>
        <a href="#" class="like"><i class="fas fa-heart fa-2x"></i></a>
    </div>
</div>

<!-- ここから -->
<script>
    // スワイプするユーザー数の定数を定義
    const usersNum = {{ form.list_length }}
        let
    currentUserIndex = 0;
    var postReaction = function (user_id, reaction) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
            }
        });
        $.ajax({
            type: "POST",
            headers: {"X-CSRFToken": getCookie("csrftoken")},
            url: "/reactions/",
            data: {
                user_id: user_id,
                reaction: reaction,
            },
            success: function (j_data) {
                console.log("success")
            }
        });
    }
    $("#tinderslide").jTinder({
        onDislike: function (item) {
            currentUserIndex++;
            checkUserNum();
            var user_id = item[0].dataset.user_id
            postReaction(user_id, 'dislike')
        },
        onLike: function (item) {
            currentUserIndex++;
            checkUserNum();
            var user_id = item[0].dataset.user_id
            postReaction(user_id, 'like')
        },
        animationRevertSpeed: 200,
        animationSpeed: 400,
        threshold: 1,
        likeSelector: '.like',
        dislikeSelector: '.dislike'
    });
    $('.actions .like, .actions .dislike').click(function (e) {
        e.preventDefault();
        $("#tinderslide").jTinder($(this).attr('class'));
    });

    function checkUserNum() {
        // スワイプするユーザー数とスワイプした回数が同じになればaddClassする
        if (currentUserIndex === usersNum) {
            $(".noUser").addClass("is-active");
            $("#actionBtnArea").addClass("is-none")
            return;
        }
    }

    function getCookie(c_name) {
        if (document.cookie.length > 0) {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1) {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) c_end = document.cookie.length;
                return unescape(document.cookie.substring(c_start, c_end));
            }
        }
        return "";
    }
</script>
<!-- ここまで --></script>